<a href="https://colab.research.google.com/github/ShreyasSubhedar/Deep_Learning/blob/master/DL%23103/SigmoidToyData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Class for Sigmoid Neruon

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.colors
import matplotlib.animation as animation
import os as os
my_cmap = matplotlib.colors.LinearSegmentedColormap.from_list("", ["red","yellow","green"])

In [0]:
class SigmoidNeuron:
  
  def __init__(self):
    self.w = None
    self.b = None
    
  def perceptron(self, x):
    return np.dot(x, self.w.T) + self.b
  
  def sigmoid(self, x):
    return 1.0/(1.0 + np.exp(-x))
  
  def grad_w(self, x, y):
    y_pred = self.sigmoid(self.perceptron(x))
    return (y_pred - y) * y_pred * (1 - y_pred) * x
  
  def grad_b(self, x, y):
    y_pred = self.sigmoid(self.perceptron(x))
    return (y_pred - y) * y_pred * (1 - y_pred)
  
  def fit(self, X, Y, epochs=1, learning_rate=1, initialise=True):
    
    # initialise w, b
    if initialise:
      self.w = np.random.randn(1, X.shape[1])
      self.b = 0
    
    for i in range(epochs):
      dw = 0
      db = 0
      for x, y in zip(X, Y):
        dw += self.grad_w(x, y)
        db += self.grad_b(x, y)       
      self.w -= learning_rate * dw
      self.b -= learning_rate * db

#Fit for Toy Data

In [0]:
X = np.asarray([[2.5, 2.5], [4, -1], [1, -4], [-3, 1.25], [-2, -4], [1, 5]])
Y = [1, 1, 1, 0, 0, 0]

In [0]:
sn = SigmoidNeuron()
sn.fit(X,Y,1,0.25,True)
for i in range(20):
  print(sn.w,sn.b)
  sn.fit(X,Y,1,0.5,False)

[[ 0.30666322 -1.01970691]] [0.01633922]
[[ 0.49792094 -0.84073839]] [0.05495539]
[[ 0.76442038 -0.52576786]] [0.09284678]
[[ 1.00296297 -0.18839583]] [0.0469917]
[[ 1.00300133 -0.45674991]] [-0.02573923]
[[ 1.14170595 -0.2878851 ]] [-0.08081469]
[[ 1.15263248 -0.45556389]] [-0.140157]
[[ 1.24419842 -0.36810449]] [-0.18563824]
[[ 1.26982407 -0.44957955]] [-0.23131746]
[[ 1.32668609 -0.42695734]] [-0.2691785]
[[ 1.36096019 -0.45700205]] [-0.30535279]
[[ 1.40064849 -0.46211206]] [-0.33771885]
[[ 1.43458013 -0.47543033]] [-0.367889]
[[ 1.46724046 -0.48525   ]] [-0.39574559]
[[ 1.49766739 -0.49511978]] [-0.42168369]
[[ 1.52636844 -0.50429326]] [-0.44589309]
[[ 1.55347713 -0.51297742]] [-0.46856844]
[[ 1.57915925 -0.52120383]] [-0.48987059]
[[ 1.60355115 -0.52901789]] [-0.50993877]
[[ 1.62677151 -0.5364575 ]] [-0.52889338]


In [0]:



def plot_sn(X, Y, sn, plt):
  X1 = np.linspace(-10, 10, 100)
  X2 = np.linspace(-10, 10, 100)
  XX1, XX2 = np.meshgrid(X1, X2)
  YY = np.zeros(XX1.shape)
  for i in range(X2.size):
    for j in range(X1.size):
      val = np.asarray([X1[j], X2[i]])
      YY[i, j] = sn.sigmoid(sn.perceptron(val))
  plt.contourf(XX1, XX2, YY, cmap=my_cmap, alpha=0.6)
  plt.scatter(X[:,0], X[:,1],c=Y, cmap=my_cmap)
  plt.plot()
  

In [0]:
sn.fit(X, Y, 1, 0.05, True)
N = 30
fig= plt.figure()
for i in range(N):
  # print(sn.w, sn.b)
  # ax = plt.subplot(N, 1, i + 1)
  plot_sn(X, Y, sn, plt)
  plt.savefig(f'full_figure{i}.png')
  plt.close()
  # fig.savefig(f'full_figure{i}.png')
  sn.fit(X, Y, 1, 0.5, False)
  


In [0]:
# !rm full_figure*.png


In [0]:
    os.system("ffmpeg -r 1 -i full_figure%01d.png -vcodec mpeg4 -y movie.mp4")

0

In [0]:
!ffmpeg -i movie.mp4 -r 16 -filter:v "setpts=0.7*PTS" movie1.mp4


ffmpeg version 3.4.6-0ubuntu0.18.04.1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.3.0-16ubuntu3)
  configuration: --prefix=/usr --extra-version=0ubuntu0.18.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --ena